spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: an902318

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379
    password:

jwt:
  secretKey: j2jk34b12b4jkb1jk4bk1b4j24bjk2b14kj21b4jb21k4b1khvfc8f7gfg7f2g78ab82ng2kj1f2dg1aaf9asf8afgyivfl3fy13f138fku1hfo1bu

  access:
    expiration: 3600000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))